### ISSUE TITLE
Redefinition of types now included in base-types

### ISSUE THREAD

**Issue by vbargsten** [rock-control/control-ctrl_types#2]
Definitions of Twist and Acceleration clash with the ones of base-types and orogen component using this package won't compile.

**Comment by dmronga** [comment]
What is the orogen component that uses this package?

**Comment by vbargsten** [comment]
control/orogen/locomotion_planner

**Comment by dmronga** [comment]
Than that task library should switch to base/types. I will add a deprecation warning to ctrl_types
